### ISSUE TITLE
Jar unable to perform export command.

### ISSUE THREAD

**Issue by syy94** [CS2103AUG2017-W15-B1/Main#75]
![image](https://user-images.githubusercontent.com/28534459/32363332-d81779a2-c0a9-11e7-8b82-a0de02e67152.png)

Below is the log files:
[addressbook.log.txt](https://github.com/CS2103AUG2017-W15-B1/Main/files/1440279/addressbook.log.txt)

I tried deleting the all the generated files (data folder, etc) and restarted the application. Still Export command does not work.

**Comment by freesoup** [comment]
Hello, the correct export command is "export Filename" as stated in the userguide. Please refer to https://github.com/CS2103AUG2017-W15-B1/Main/blob/master/docs/UserGuide.adoc#exporting-contacts-code-export-code

However we realise that the error message is a bit ambiguous. Thanks for informing us!

**Comment by syy94** [comment]
![image](https://user-images.githubusercontent.com/28534459/32367145-16f1e484-c0bc-11e7-90e0-1c565839344d.png)

Oh sry i only referred to the in-app user guide (F1 key). So guess the in app one was not generated properly. But i noticed that im using v1.4 so this issue may be outdated.

**Comment by freesoup** [comment]
Alright, thanks for clarifying! It was our release that was outdated. So sorry about it.

**Comment by john19950730** [comment]
New version of Rubrika has already been released, in fact the next version after that will be released within the next 24 hours. Issue will be closed.
