### ISSUE TITLE
History command does not work.

### ISSUE THREAD

**Issue by erik0704** [CS2103AUG2017-W15-B1/Main#77]

**Comment by freesoup** [comment]
Could you provide a description of the problem? Thanks

**Comment by erik0704** [comment]
Hm it seems like when I first loaded the jar file the `ResultDisplay` box did not work at all for some reason.
Thus resulting in most of the issues I listed.

After I restart the application it works as expected. I am unable to reproduce so far as to what trigger the `ResultDisplay` UI component to fail unfortunately.

**Comment by john19950730** [comment]
Seems like this issue is caused by the bug highlighted in the other issue. Closing.
