### ISSUE TITLE
Sort command is not redo/undo-able. 

### ISSUE THREAD

**Issue by erik0704** [CS2103AUG2017-W15-B1/Main#78]
If this is the intended behavior maybe document it somewhere ?

**Comment by freesoup** [comment]
Hello it was the intended behavior as sort command does nothing to the internal addressbook list. We simply arrange what is shown to the user. Hence there is nothing to undo. 

However, we do realize the documentation was a bit unclear. Thanks for informing us.

**Comment by john19950730** [comment]
Clarifications will be made to the documentation published in the coming developmental cycle.
In fact changes have already been made and is awaiting integration with other changes to documentations.
Issue will be closed.
