### ISSUE TITLE
Documentation ambiguity

### ISSUE THREAD

**Issue by erik0704** [CS2103AUG2017-W15-B1/Main#80]
- `add` command shortcut (`a`) may have clearer instruction in the user guide, i.e. the example `a ...` does not work, as it's supposed to work with a tab for autocomplete.

- `find A gets completed with all possible keywords starting with A` in autocomplete section of user guide . What does "all possible keywords" here means? I try `find B` when there's 2 people whose name start with B and it only autocomplete to one.

- `theme` features is not documented properly.

**Comment by john19950730** [comment]
Hi, thanks for testing out our application. I would like to respond to your comments as follows:

First of all, thanks for pointing out the mistake in the User Guide, the command shortcut has been removed for all commands.

Secondly, can you please provide the test data you have used, a screenshot will be appreciated, preferably showing all names starting with `B` when you use the command.

Thirdly, thank you for pointing out the missing section in the User Guide, your help is appreciated.

**Comment by john19950730** [comment]
@kosyoz Would appreciate more detailed explanation of `theme` command for the coming version, thanks!

**Comment by john19950730** [comment]
Relevant changes to documentation with respect to your first and second point has already been made, undergoing integration for the coming version, thank you once again for pointing out the mistakes in our documentation.

**Comment by john19950730** [comment]
Documentation has been updated to provide more details about `theme` command to make it more user-friendly. Closing.
